import adapter from "@sveltejs/adapter-vercel";
import { sveltekit } from "@sveltejs/kit/vite";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig, lazyPlugins } from "vite-plus";

// Keep in sync with src/lib/images.ts; Vercel only serves widths listed here.
const IMAGE_SIZES = [96, 192, 256, 384, 512, 768];

export default defineConfig({
  define: {
    __VERCEL_IMAGES__: JSON.stringify(process.env.VERCEL === "1"),
  },
  fmt: {
    // Generated by scripts/sync-pokedex.ts; kept one entry per line for readable diffs.
    ignorePatterns: ["src/lib/data/*.json", "drizzle/**"],
  },
  lint: {
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
    options: { typeAware: true, typeCheck: true },
  },
  test: {
    include: ["src/**/*.test.ts", "scripts/**/*.test.ts"],
  },
  plugins: lazyPlugins(() => [
    tailwindcss(),
    sveltekit({
      compilerOptions: {
        // Force runes mode for the project, except for libraries. Can be removed in svelte 6.
        runes: ({ filename }) =>
          filename.split(/[/\\]/).includes("node_modules") ? undefined : true,
      },
      adapter: adapter({
        runtime: "nodejs24.x",
        images: {
          sizes: IMAGE_SIZES,
          domains: ["raw.githubusercontent.com"],
          formats: ["image/avif", "image/webp"],
          minimumCacheTTL: 60 * 60 * 24 * 30,
        },
      }),
    }),
  ]),
});
